// Dev tool: writes consensus-events.js (topic0 and inputs of every event of Bradbury's consensus
// contract) from the genlayer-js ABI, so the collector can decode logs without a library.
//
//   node collector/core/build-events.mjs

import { writeFileSync } from "node:fs";
import { dirname, join } from "node:path";
import { fileURLToPath } from "node:url";
import { testnetBradbury } from "genlayer-js/chains";
import { toEventSelector } from "viem";

const C = testnetBradbury.consensusMainContract;
const events = {};
for (const e of C.abi.filter((x) => x.type === "event")) {
  const sig = `${e.name}(${e.inputs.map((i) => i.type).join(",")})`;
  events[toEventSelector(sig)] = { name: e.name, inputs: e.inputs.map((i) => ({ name: i.name, type: i.type, indexed: !!i.indexed })) };
}
const out = { source: "genlayer-js 1.2.0, chains.testnetBradbury.consensusMainContract", address: C.address, events };
writeFileSync(join(dirname(fileURLToPath(import.meta.url)), "consensus-events.js"),
  "// Generated by build-events.mjs. Do not edit.\nexport default " + JSON.stringify(out, null, 1) + ";\n");
console.log(`${Object.keys(events).length} events, contract ${C.address}`);
