// Generated by build-events.mjs. Do not edit.
export default {
 "source": "genlayer-js 1.2.0, chains.testnetBradbury.consensusMainContract",
 "address": "0x0112Bf6e83497965A5fdD6Dad1E447a6E004271D",
 "events": {
  "0xf7861b60d3b514908b00c1461e500857f819123764586496fcddba2eb034c94c": {
   "name": "ActivatorReplaced",
   "inputs": [
    {
     "name": "txId",
     "type": "bytes32",
     "indexed": true
    },
    {
     "name": "oldActivator",
     "type": "address",
     "indexed": true
    },
    {
     "name": "newActivator",
     "type": "address",
     "indexed": true
    }
   ]
  },
  "0x2e967678ac371453fc8babb3af60134332176ca4334ac0032e7b2a655c72e5a9": {
   "name": "AddressManagerSet",
   "inputs": [
    {
     "name": "addressManager",
     "type": "address",
     "indexed": true
    }
   ]
  },
  "0xb61dd9b213508bbd8e6c89d7c254d830e0ed7e8cd5bd4163a167a47b12e46e81": {
   "name": "AllVotesCommitted",
   "inputs": [
    {
     "name": "txId",
     "type": "bytes32",
     "indexed": true
    },
    {
     "name": "newStatus",
     "type": "uint8",
     "indexed": false
    }
   ]
  },
  "0x08e6523db104b48b6f1a359653498b9739ec31f6e03abb21e7acf4d73f0a48ff": {
   "name": "AppealStarted",
   "inputs": [
    {
     "name": "txId",
     "type": "bytes32",
     "indexed": true
    },
    {
     "name": "appellant",
     "type": "address",
     "indexed": true
    },
    {
     "name": "bond",
     "type": "uint256",
     "indexed": false
    },
    {
     "name": "validators",
     "type": "address[]",
     "indexed": false
    }
   ]
  },
  "0x3d139c84ad9350b1f396f3d75cb0770c4f495459f8ef8755e5335a12632bac3d": {
   "name": "BatchFinalizationCompleted",
   "inputs": [
    {
     "name": "attempted",
     "type": "uint256",
     "indexed": false
    },
    {
     "name": "succeeded",
     "type": "uint256",
     "indexed": false
    },
    {
     "name": "failed",
     "type": "uint256",
     "indexed": false
    }
   ]
  },
  "0x8620e7f03a280a3d2aa84bd41ba19524c2d7f1dbfa9d79cb81877b0f8c963f9b": {
   "name": "CreatedTransaction",
   "inputs": [
    {
     "name": "txId",
     "type": "bytes32",
     "indexed": true
    },
    {
     "name": "txSlot",
     "type": "uint256",
     "indexed": false
    }
   ]
  },
  "0xc7f505b2f371ae2175ee4913f4499e1f2633a7b5936321eed1cdaeb6115181d2": {
   "name": "Initialized",
   "inputs": [
    {
     "name": "version",
     "type": "uint64",
     "indexed": false
    }
   ]
  },
  "0xfcd4925545581224af98ce36b42d51bb88917ea0c3fe675c27e1df1a22282555": {
   "name": "InternalMessageProcessed",
   "inputs": [
    {
     "name": "txId",
     "type": "bytes32",
     "indexed": true
    },
    {
     "name": "recipient",
     "type": "address",
     "indexed": true
    },
    {
     "name": "activator",
     "type": "address",
     "indexed": true
    }
   ]
  },
  "0x1c717affb0f2d0bd7bccd509af90bc762d34bc45ad812ef154a3f5efdae1ca6b": {
   "name": "LeaderIdlenessProcessed",
   "inputs": [
    {
     "name": "txId",
     "type": "bytes32",
     "indexed": true
    },
    {
     "name": "oldLeader",
     "type": "address",
     "indexed": true
    },
    {
     "name": "newLeader",
     "type": "address",
     "indexed": true
    }
   ]
  },
  "0xdab9102861c7483a187584d6371d88316f005af507982ccf95c110879f3ed5a5": {
   "name": "NewTransaction",
   "inputs": [
    {
     "name": "txId",
     "type": "bytes32",
     "indexed": true
    },
    {
     "name": "recipient",
     "type": "address",
     "indexed": true
    },
    {
     "name": "activator",
     "type": "address",
     "indexed": true
    }
   ]
  },
  "0x38d16b8cac22d99fc7c124b9cd0de2d3fa1faef420bfe791d8c362d765e22700": {
   "name": "OwnershipTransferStarted",
   "inputs": [
    {
     "name": "previousOwner",
     "type": "address",
     "indexed": true
    },
    {
     "name": "newOwner",
     "type": "address",
     "indexed": true
    }
   ]
  },
  "0x8be0079c531659141344cd1fd0a4f28419497f9722a3daafe3b4186f6b6457e0": {
   "name": "OwnershipTransferred",
   "inputs": [
    {
     "name": "previousOwner",
     "type": "address",
     "indexed": true
    },
    {
     "name": "newOwner",
     "type": "address",
     "indexed": true
    }
   ]
  },
  "0x6ae3550300804fa352835a3e1279593d83ce88e20c9feb43302db45b1d89e6c9": {
   "name": "ProcessIdlenessAccepted",
   "inputs": [
    {
     "name": "txId",
     "type": "bytes32",
     "indexed": true
    }
   ]
  },
  "0xf250caa116f9eac0e4e82d403f131ce0a520b6c232dbcbe270b3729b0aaca09e": {
   "name": "TransactionAccepted",
   "inputs": [
    {
     "name": "txId",
     "type": "bytes32",
     "indexed": true
    }
   ]
  },
  "0x1081f7638e5a02d916250da410b76a0821bdb2b09c574c0f237830409c37d0c8": {
   "name": "TransactionActivated",
   "inputs": [
    {
     "name": "txId",
     "type": "bytes32",
     "indexed": true
    },
    {
     "name": "leader",
     "type": "address",
     "indexed": true
    }
   ]
  },
  "0x0a94f6cf3e473cb72e765b24d1365bfcbef8d31a73215bb27e50df39757f578a": {
   "name": "TransactionCancelled",
   "inputs": [
    {
     "name": "txId",
     "type": "bytes32",
     "indexed": true
    },
    {
     "name": "cancelledBy",
     "type": "address",
     "indexed": true
    }
   ]
  },
  "0xd157a8824e3093207095e0855163da28b596e2c5f19ba73ea473c2346e05b15b": {
   "name": "TransactionFinalizationFailed",
   "inputs": [
    {
     "name": "txId",
     "type": "bytes32",
     "indexed": true
    }
   ]
  },
  "0x24196ec40f90671b7144e716978686b4f3c7d6b00b23da3971ef2b52af27d87f": {
   "name": "TransactionFinalized",
   "inputs": [
    {
     "name": "txId",
     "type": "bytes32",
     "indexed": true
    }
   ]
  },
  "0x17aad8cee7fa654be58106f05c4040122273bad66e94979ffbb9f7ecccc68c5e": {
   "name": "TransactionLeaderRevealed",
   "inputs": [
    {
     "name": "txId",
     "type": "bytes32",
     "indexed": true
    }
   ]
  },
  "0x42dd93d103ec25ce3ac597cec3f3aa55b91b52ffa90a04f9e14545f4543e7c48": {
   "name": "TransactionLeaderRotated",
   "inputs": [
    {
     "name": "txId",
     "type": "bytes32",
     "indexed": true
    },
    {
     "name": "newLeader",
     "type": "address",
     "indexed": true
    }
   ]
  },
  "0xe51a41760ba25c8a4ac33894d5eb8698cf110a90d4e6f764fa0579ec8767b466": {
   "name": "TransactionLeaderTimeout",
   "inputs": [
    {
     "name": "txId",
     "type": "bytes32",
     "indexed": true
    }
   ]
  },
  "0x9c4bf38aa77ce1103eb348ff99a695363c0b42ab316945b0e19906310f2146a2": {
   "name": "TransactionNeedsRecomputation",
   "inputs": [
    {
     "name": "txIds",
     "type": "bytes32[]",
     "indexed": false
    }
   ]
  },
  "0xeeb84a2b70442f0f7263c2cc055eaaba369bc7f3d87dd784346cb4ed69679035": {
   "name": "TransactionReceiptProposed",
   "inputs": [
    {
     "name": "txId",
     "type": "bytes32",
     "indexed": true
    },
    {
     "name": "validators",
     "type": "address[]",
     "indexed": false
    }
   ]
  },
  "0xb9f69df2250e1788b862d0715b1dad98b2a50311c017ebb71f6cd83de656b06d": {
   "name": "TransactionUndetermined",
   "inputs": [
    {
     "name": "txId",
     "type": "bytes32",
     "indexed": true
    }
   ]
  },
  "0x6565c26927b368d6e75314c8bf1c1e2847f1cdd47b89e10ae002a2889da4d150": {
   "name": "UnissuedMessagesAtFinalization",
   "inputs": [
    {
     "name": "txId",
     "type": "bytes32",
     "indexed": true
    },
    {
     "name": "totalUnissuedValue",
     "type": "uint256",
     "indexed": false
    },
    {
     "name": "unissuedCount",
     "type": "uint256",
     "indexed": false
    }
   ]
  },
  "0xb9adb9860846c6726d973e93f6d5994ba6aa797233e2d15851d42e9c68a5dd72": {
   "name": "ValidatorReplaced",
   "inputs": [
    {
     "name": "txId",
     "type": "bytes32",
     "indexed": true
    },
    {
     "name": "oldValidator",
     "type": "address",
     "indexed": true
    },
    {
     "name": "newValidator",
     "type": "address",
     "indexed": true
    },
    {
     "name": "validatorIndex",
     "type": "uint256",
     "indexed": false
    }
   ]
  },
  "0xd7d0ee861c0ebf42599b922e8f4ad0cafed951841610157bcd56110f49ced8ee": {
   "name": "ValueWithdrawalFailed",
   "inputs": [
    {
     "name": "txId",
     "type": "bytes32",
     "indexed": true
    },
    {
     "name": "recipient",
     "type": "address",
     "indexed": true
    },
    {
     "name": "value",
     "type": "uint256",
     "indexed": false
    }
   ]
  },
  "0xc5dd23f5cc17858ca1e3d0f06cbcc78820753b0dd2fea89d03d0d842192c1531": {
   "name": "VoteCommitted",
   "inputs": [
    {
     "name": "txId",
     "type": "bytes32",
     "indexed": true
    },
    {
     "name": "validator",
     "type": "address",
     "indexed": true
    },
    {
     "name": "isLastVote",
     "type": "bool",
     "indexed": false
    }
   ]
  },
  "0x14d4bda97d7d28622aa0ad6e4d069bb9215b9e2346ecbdf2313b04121da0b68a": {
   "name": "VoteRevealed",
   "inputs": [
    {
     "name": "txId",
     "type": "bytes32",
     "indexed": true
    },
    {
     "name": "validator",
     "type": "address",
     "indexed": true
    },
    {
     "name": "voteType",
     "type": "uint8",
     "indexed": false
    },
    {
     "name": "isLastVote",
     "type": "bool",
     "indexed": false
    },
    {
     "name": "result",
     "type": "uint8",
     "indexed": false
    }
   ]
  }
 }
};
